runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static.*
  static_dir: static
  login: required
- url: /.*
  script: main.app
  login: required
- url: /
  static_files: static/schedule.html
  upload: static/schedule.html
- url: /static.*
  static_dir: static
- url: /.*
  script: main.app




libraries:
- name: jinja2
  version: latest
